#docker compose to run local mysql
version: '3.1'
services:
  db:
    image: mysql:lts
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
